name: Deploy docker with app

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d "${{ secrets.LOCATION }}${{ github.event.repository.name }}-${{ github.ref_name }}" ]; then
                cd "${{ secrets.LOCATION }}${{ github.event.repository.name }}-${{ github.ref_name }}"
                git pull origin ${{ github.ref_name }}
            else
                cd ${{ secrets.LOCATION }}
                git clone --branch ${{ github.ref_name }} https://github.com/${{ github.repository }} "${{ secrets.LOCATION }}${{ github.event.repository.name }}-${{ github.ref_name }}"
            fi
            docker rm -f ${{ github.event.repository.name }}-${{ github.ref_name }}
            docker rmi  ${{ github.event.repository.name }}-${{ github.ref_name }}
            docker build -t ${{ github.event.repository.name }}-${{ github.ref_name }} "${{ secrets.LOCATION }}${{ github.event.repository.name }}-${{ github.ref_name }}" 
            docker run -d --name ${{ github.event.repository.name }}-${{ github.ref_name }} ${{ github.event.repository.name }}-${{ github.ref_name }}
