name: Deploy docker with app

on:
  push:
    branches:
      - master
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Docker container to EC2
        env:
          IMAGE: ${{ github.repository }}-${{ github.ref_name }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          LOCATION: ${{ secrets.LOCATION }}
          REPO_DIR: "${{ secrets.LOCATION }}${{ github.repository }}-${{ github.ref_name }}"
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_KEY $USER_NAME@$EC2_HOST << 'EOF'
          if [ -d "$REPO_DIR" ]; then
              cd $REPO_DIR
              git pull origin ${{ github.ref_name }}
          else
              cd $LOCATION
              git clone --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}
          fi
          docker rm -f $IMAGE || true
          docker rmi -f $IMAGE || true
          docker build -t $IMAGE . 
          docker run -d --name $IMAGE $IMAGE 
          EOF
