name: Deploy docker with app

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE: ${{ github.repository }}-${{ github.ref_name }}
          LOCATION: ${{ secrets.LOCATION }}
          REPO_DIR: "${{ secrets.LOCATION }}${{ github.repository }}-${{ github.ref_name }}"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d "$REPO_DIR" ]; then
                cd $REPO_DIR
                git pull origin ${{ github.ref_name }}
            else
                cd $LOCATION
                git clone --branch ${{ github.ref_name }} https://github.com/${{ github.repository }} $REPO_DIR
            fi
            docker rm -f $IMAGE || true
            docker rmi -f $IMAGE || true
            docker build -t $IMAGE . 
            docker run -d --name $IMAGE $IMAGE 
            EOF
