name: Run Tests and Generate Coverage

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -s tests -p 'test_*.py'
          coverage report -m > coverage.txt

      - name: Run tests and capture output
        id: run_tests
        run: |
          pytest_output=$(pytest)
          echo "::set-output name=pytest_output::$pytest_output"  # Store pytest output as an action output

      - name: Comment on pull request with pytest output
        uses: unsplash/comment-on-pr@v1.3.0
        with:
          msg: |
            Pytest Output:
            ```
            ${{ steps.run_tests.outputs.pytest_output }}
            ```
            
            Coverage Report:
            ```
            $(cat coverage.txt)
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}