name: Run Tests and Generate Coverage

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -s tests -p 'test_*.py'
          coverage report -m > coverage.txt
