name: Run Tests and Generate Coverage

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests and capture output
        id: run_tests
        run: |
          set -x
          pytest_output=$(pytest)
          set +x
          echo "::set-output name=pytest_output::$pytest_output"

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -s tests -p 'test_*.py'
          coverage report -m > coverage.txt

      - name: Read coverage file
        id: coverage
        run: |
          echo "::set-output name=coverage_content::$(cat coverage.txt)"

      - name: Install deps
        run: pip install pytest-md pytest-emoji

      - name: Run pytestss
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: "-q"
          click-to-expand: true
          report-title: "PyTest Report"

      - name: Comment on pull request with pytest output
        uses: unsplash/comment-on-pr@v1.3.0
        with:
          msg: |
            Pytest:
            ```
            ${{ steps.run_tests.outputs.pytest_output }}

            ```

            Coverage Report:
            ```

            $(echo "${{ steps.coverage.outputs.coverage_content }}")
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
